DROP TABLE SETTINGS IF EXISTS;
DROP TABLE NTP_SERVER IF EXISTS;

CREATE TABLE IF NOT EXISTS NTP_SERVER
(
	ID INTEGER IDENTITY PRIMARY KEY,
	NAME VARCHAR(255),
	HOST VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SETTINGS
(
	ID INTEGER IDENTITY PRIMARY KEY,
	VERSION INTEGER DEFAULT 0,								-- Version of the database
	FK_NTP_SERVER INTEGER NOT NULL,							-- The current NTP server
	FOREIGN KEY(FK_NTP_SERVER) REFERENCES NTP_SERVER(ID)
);

